# Generated by Django 4.2.20 on 2025-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('open', 'Open'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='new', max_length=20),
        ),
    ]
