# Generated by Django 4.2.25 on 2025-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_update_lead_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_summaries',
            field=models.JSONField(blank=True, default=list, help_text='List of call summary entries for this lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('open', 'Open'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up')], default='new', max_length=20),
        ),
    ]
