# Generated by Django 4.2.25 on 2025-11-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def remove_call_summaries_field_if_exists(apps, schema_editor):
    """Remove call_summaries field from Lead model only if it exists"""
    db_table = 'leads_lead'
    column_name = 'call_summaries'
    
    with schema_editor.connection.cursor() as cursor:
        # Get current database name
        cursor.execute("SELECT DATABASE()")
        db_name = cursor.fetchone()[0]
        
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME = %s
            AND COLUMN_NAME = %s
        """, [db_name, db_table, column_name])
        
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            # Drop the column using raw SQL
            cursor.execute(f"ALTER TABLE {db_table} DROP COLUMN {column_name}")


def reverse_remove_call_summaries_field(apps, schema_editor):
    """Reverse migration - this is a no-op since we can't recreate the field"""
    pass


def create_leadcallsummary_table_if_not_exists(apps, schema_editor):
    """Create LeadCallSummary table only if it doesn't exist"""
    db_table = 'leads_leadcallsummary'
    
    with schema_editor.connection.cursor() as cursor:
        # Get current database name
        cursor.execute("SELECT DATABASE()")
        db_name = cursor.fetchone()[0]
        
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME = %s
        """, [db_name, db_table])
        
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Table doesn't exist, create it manually using SQL
            # This matches the CreateModel definition below
            cursor.execute(f"""
                CREATE TABLE {db_table} (
                    created_at DATETIME(6) NOT NULL,
                    updated_at DATETIME(6) NOT NULL,
                    id CHAR(36) NOT NULL PRIMARY KEY,
                    summary LONGTEXT NOT NULL,
                    call_time DATETIME(6) NULL,
                    is_active BOOLEAN NOT NULL,
                    created_by_id CHAR(36) NULL,
                    lead_id CHAR(36) NOT NULL,
                    tenant_id CHAR(36) NOT NULL,
                    FOREIGN KEY (created_by_id) REFERENCES user_customuser(id) ON DELETE SET NULL,
                    FOREIGN KEY (lead_id) REFERENCES leads_lead(id) ON DELETE CASCADE,
                    FOREIGN KEY (tenant_id) REFERENCES user_tenant(id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            # Create indexes
            cursor.execute(f"CREATE INDEX leads_leadc_tenant__edc95f_idx ON {db_table} (tenant_id, lead_id, created_at)")
            cursor.execute(f"CREATE INDEX leads_leadc_tenant__7299c5_idx ON {db_table} (tenant_id, created_at)")


def reverse_create_leadcallsummary_table(apps, schema_editor):
    """Reverse migration - this is handled by the CreateModel reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0006_lead_call_summaries_alter_lead_status'),
    ]

    operations = [
        # Conditionally remove field only if it exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_call_summaries_field_if_exists,
                    reverse_remove_call_summaries_field,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='lead',
                    name='call_summaries',
                ),
            ],
        ),
        # Conditionally create table only if it doesn't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_leadcallsummary_table_if_not_exists,
                    reverse_create_leadcallsummary_table,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LeadCallSummary',
                    fields=[
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('summary', models.TextField(help_text='Detailed call summary')),
                        ('call_time', models.DateTimeField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_call_summaries', to=settings.AUTH_USER_MODEL)),
                        ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_summaries', to='leads.lead')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_call_summaries', to='user.tenant')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['tenant', 'lead', 'created_at'], name='leads_leadc_tenant__edc95f_idx'), models.Index(fields=['tenant', 'created_at'], name='leads_leadc_tenant__7299c5_idx')],
                    },
                ),
            ],
        ),
    ]
