# Generated by Django 4.2.25 on 2025-11-07 12:09

from django.db import migrations, models
import json


def convert_text_to_json(apps, schema_editor):
    """Convert existing text summary to JSON format before changing column type"""
    LeadCallSummary = apps.get_model('leads', 'LeadCallSummary')
    
    with schema_editor.connection.cursor() as cursor:
        # Get all summaries
        cursor.execute("SELECT id, summary FROM leads_leadcallsummary")
        rows = cursor.fetchall()
        
        for row_id, summary_text in rows:
            if summary_text is None or summary_text == '':
                # Set NULL values to empty JSON object
                json_value = json.dumps({})
            else:
                try:
                    # Try to parse as JSON - if it's already valid JSON, keep it
                    parsed = json.loads(summary_text)
                    json_value = json.dumps(parsed)  # Re-serialize to ensure it's valid
                except (json.JSONDecodeError, TypeError):
                    # Not valid JSON, wrap it in a JSON object
                    json_value = json.dumps({"text": str(summary_text)})
            
            # Update the row with valid JSON
            cursor.execute(
                "UPDATE leads_leadcallsummary SET summary = %s WHERE id = %s",
                [json_value, row_id]
            )


def reverse_convert_json_to_text(apps, schema_editor):
    """Reverse: extract text from JSON"""
    LeadCallSummary = apps.get_model('leads', 'LeadCallSummary')
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, summary FROM leads_leadcallsummary WHERE summary IS NOT NULL")
        rows = cursor.fetchall()
        
        for row_id, summary_json in rows:
            if summary_json:
                try:
                    data = json.loads(summary_json)
                    # Extract text if it's a dict with 'text' key, otherwise use the whole thing
                    if isinstance(data, dict) and 'text' in data:
                        text_value = data['text']
                    else:
                        text_value = str(data)
                    cursor.execute(
                        "UPDATE leads_leadcallsummary SET summary = %s WHERE id = %s",
                        [text_value, row_id]
                    )
                except (json.JSONDecodeError, TypeError):
                    # Already text, skip
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_call_summaries_leadcallsummary'),
    ]

    operations = [
        migrations.RunPython(
            convert_text_to_json,
            reverse_convert_json_to_text,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE leads_leadcallsummary 
                        MODIFY COLUMN summary JSON
                    """,
                    reverse_sql="""
                        ALTER TABLE leads_leadcallsummary 
                        MODIFY COLUMN summary LONGTEXT
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='leadcallsummary',
                    name='summary',
                    field=models.JSONField(help_text='Detailed call summary as JSON object'),
                ),
            ],
        ),
    ]
