# Generated by Django 4.2.25 on 2025-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_change_summary_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcallsummary',
            name='summary',
            field=models.TextField(help_text='Detailed call summary'),
        ),
    ]
