# Generated by Django 4.2.20 on 2025-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_leadcallsummary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcallsummary',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('scheduled_meeting', 'Scheduled Meeting'), ('sent_info', 'Sent Info'), ('ended_call', 'Ended Call'), ('thanked_ended', 'Thanked and Ended')], help_text='Final outcome of the call', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q1_interested_future',
            field=models.BooleanField(blank=True, help_text='Q1 Follow-up: Are you interested in U.S. residency in the future? (Only if Q1 was NO)', null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q1_preparing_usmle_residency',
            field=models.BooleanField(blank=True, help_text='Q1: Are you currently preparing for USMLE or applying for U.S. residency?', null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q2_clinical_research_opportunities',
            field=models.BooleanField(blank=True, help_text='Q2: Are you looking for U.S. clinical experience or research opportunities?', null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q2_want_to_learn_more',
            field=models.BooleanField(blank=True, help_text='Q2 Follow-up: These really strengthen residency applications. Want to learn more? (Only if Q2 was NO)', null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q3_preference',
            field=models.CharField(blank=True, choices=[('call', 'Free 1-on-1 Call'), ('info', 'Detailed Info Only'), ('both', 'Both Call and Info'), ('none', 'No to Both')], help_text='Q3: Would you like detailed info sent to you, or prefer a free 1-on-1 call?', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leadcallsummary',
            name='q3_want_call_after_info',
            field=models.BooleanField(blank=True, help_text="Q3 Follow-up: Great! Info coming your way. Sure you don't want the free call too? (Only if Q3 was 'info')", null=True),
        ),
        migrations.AlterField(
            model_name='leadcallsummary',
            name='summary',
            field=models.TextField(blank=True, help_text='Additional detailed call summary or notes', null=True),
        ),
        migrations.AddIndex(
            model_name='leadcallsummary',
            index=models.Index(fields=['call_outcome'], name='leads_leadc_call_ou_df2718_idx'),
        ),
    ]
