# Generated by Django 4.2.25 on 2025-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadcallsummary_call_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcallsummary',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('scheduled_meeting', 'Scheduled Meeting'), ('sent_info', 'Sent Info'), ('ended_call', 'Ended Call'), ('thanked_ended', 'Thanked and Ended'), ('follow_up', 'Follow Up'), ('not_contacted', 'Not Contacted')], help_text='Final outcome of the call', max_length=20, null=True),
        ),
    ]
