# Generated by Django 4.2.25 on 2025-11-04 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_passwordresetotp'),
        ('customer', '0004_ensure_customerhistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], help_text='Type of action performed', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Field that was changed', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Complete snapshot of all field changes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change', null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_changes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customer.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='user.tenant')),
            ],
            options={
                'verbose_name': 'Customer History',
                'verbose_name_plural': 'Customer Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customer_cu_custome_cb020b_idx'), models.Index(fields=['tenant', 'created_at'], name='customer_cu_tenant__33f174_idx'), models.Index(fields=['action', 'created_at'], name='customer_cu_action_7efb1a_idx')],
            },
        ),
    ]
