# Generated by Django 4.2.25 on 2025-10-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], help_text='HTTP method used', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint accessed', max_length=500)),
                ('request_data', models.JSONField(blank=True, help_text='Request payload data', null=True)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Request execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant context for the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_histor_user_id_a50bd6_idx'), models.Index(fields=['tenant', 'created_at'], name='user_histor_tenant__24bb3d_idx'), models.Index(fields=['method', 'created_at'], name='user_histor_method_5dc7e7_idx'), models.Index(fields=['endpoint', 'created_at'], name='user_histor_endpoin_f0e730_idx')],
            },
        ),
    ]
