# Generated by Django 4.2.25 on 2026-01-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Branch code or identifier', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the branch', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='user.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BranchHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], help_text='Type of action performed', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Field that was changed', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Complete snapshot of all field changes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='branch.branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_changes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_history', to='user.tenant')),
            ],
            options={
                'verbose_name': 'Branch History',
                'verbose_name_plural': 'Branch Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'created_at'], name='branch_bran_branch__360e6c_idx'), models.Index(fields=['tenant', 'created_at'], name='branch_bran_tenant__4129a9_idx'), models.Index(fields=['action', 'created_at'], name='branch_bran_action_2bf3bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'name'], name='branch_bran_tenant__96dccc_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'code'], name='branch_bran_tenant__93fa53_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'city'], name='branch_bran_tenant__ee77c1_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'is_active'], name='branch_bran_tenant__59a4f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('tenant', 'code')},
        ),
    ]
